import { json } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";
import Card from "../components/streaks/Card";
import TitleBar from "../components/streaks/TitleBar";
import { useState } from "react";
import AddForm from "../components/streaks/AddForm";
import Modal from "../components/common/Modal";

export const loader = async () => {
  return json([
    {
      id: 1,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 2,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },    {
      id: 3,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 4,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 5,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 6,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 1,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 2,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },    {
      id: 3,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 4,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 5,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 6,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 1,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 2,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },    {
      id: 3,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 4,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 5,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 6,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 1,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 2,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },    {
      id: 3,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 4,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 5,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 6,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 1,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 2,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },    {
      id: 3,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 4,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 5,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 6,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 1,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 2,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },    {
      id: 3,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 4,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 5,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 6,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },{
      id: 1,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 2,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },    {
      id: 3,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 4,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 5,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 6,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 1,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 2,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },    {
      id: 3,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 4,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 5,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 6,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 1,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 2,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },    {
      id: 3,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 4,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 5,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 6,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 1,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 2,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },    {
      id: 3,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 4,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 5,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 6,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 1,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 2,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },    {
      id: 3,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 4,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
    {
      id: 5,
      name: "Water bottle",
      description: "Drink 1 liter of water every day",
      created: "2023-04-01",
      strk_started: "2023-04-10",
      longest: 4,
    },
    {
      id: 6,
      name: "Stretching",
      description: "Do at least 10 minutes of stretching every day",
      created: "2023-02-25",
      strk_started: "2023-03-15",
      longest: 30,
    },
  ]);
};

export default function Streaks() {
  const [showModal, setShowModal] = useState(true)
  const goals = useLoaderData();

  const displayModal = () => {
    if (!showModal) {
      setShowModal(true);
    }
  }

  return (
    <div className="flex-1 bg-primary">
      <TitleBar title="My Streaks" handleClick={() => displayModal()}/>
      <div className="bg-primary w-full h-full px-6 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 overflow-scroll">
        {goals.map(goal => <Card key={goal.id} goal={goal} />)}
      </div>
      {showModal && <Modal>
        <AddForm closeAction={() => setShowModal(false)} showForm={showModal} />
      </Modal>}
    </div>
  );
}
